# Generated by Django 5.0.3 on 2024-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default=1, upload_to='service_img/'),
            preserve_default=False,
        ),
    ]
