# Generated by Django 5.0.3 on 2024-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_data_blog_name_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar_img/'),
            preserve_default=False,
        ),
    ]
