# Generated by Django 5.0.3 on 2024-07-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
